CREATE OR REPLACE PACKAGE BODY USR_TURISMO_REAL.PCK_TRABAJADORES IS

PROCEDURE P_LISTAR_TRABAJADORES (OUT_WORKERS   OUT SYS_REFCURSOR
                                ,OUT_RETURNCODE OUT NUMBER) IS
    BEGIN
        OPEN OUT_WORKERS FOR
        SELECT *
        FROM T_TRABAJADOR;
        
        OUT_RETURNCODE := 1;
    EXCEPTION
        WHEN OTHERS THEN BEGIN
            OUT_RETURNCODE := 0;
        END;
    END;

END PCK_TRABAJADORES;
/