CREATE OR REPLACE PACKAGE USR_TURISMO_REAL.PCK_GRAFICOS IS 
                   
PROCEDURE P_DATOS_GRAFICO       (OUT_PAGOS          OUT SYS_REFCURSOR
                                ,OUT_RETURNCODE     OUT NUMBER);
   
   
END PCK_GRAFICOS;
/