-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-09-16 15:39:05 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_categoriamantencion (
    id_categoriamantencion NUMBER NOT NULL,
    descripcion            VARCHAR2(100)
);

ALTER TABLE t_categoriamantencion ADD CONSTRAINT categoriamantencion_pk PRIMARY KEY ( id_categoriamantencion );

CREATE TABLE t_categoriareporte (
    id_categoria NUMBER NOT NULL,
    nombre       VARCHAR2(50)
);

ALTER TABLE t_categoriareporte ADD CONSTRAINT categoriareporte_pk PRIMARY KEY ( id_categoria );

CREATE TABLE t_categoriaservicio (
    id_categoriaservicio NUMBER NOT NULL,
    descripcion          VARCHAR2(100)
);

ALTER TABLE t_categoriaservicio ADD CONSTRAINT categoriaservicio_pk PRIMARY KEY ( id_categoriaservicio );

CREATE TABLE t_categoriaservicioextra (
    id_servicioextra NUMBER NOT NULL,
    nombre           VARCHAR2(50),
    descripcion      VARCHAR2(100)
);

ALTER TABLE t_categoriaservicioextra ADD CONSTRAINT servicioextra_pk PRIMARY KEY ( id_servicioextra );

CREATE TABLE t_chofer (
    id_chofer       NUMBER NOT NULL,
    nombres         VARCHAR2(50),
    apellidos       VARCHAR2(50),
    patentevehiculo VARCHAR2(50)
);

ALTER TABLE t_chofer ADD CONSTRAINT chofer_pk PRIMARY KEY ( id_chofer );

--  ERROR: Table name length exceeds maximum allowed length(30) 
CREATE TABLE t_conector_departamento_servicio (
    id_servicio     NUMBER NOT NULL,
    id_departamento NUMBER NOT NULL,
    cantidad        NUMBER,
    estado          CHAR(1)
);

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicio ADD CONSTRAINT conector_departamento_servicio_pk PRIMARY KEY ( id_servicio,
                                                                                                            id_departamento );

--  ERROR: Table name length exceeds maximum allowed length(30) 
CREATE TABLE t_conector_departamento_servicioextra (
    id_departamento    NUMBER NOT NULL,
    id_servicioextra   NUMBER NOT NULL,
    valor              NUMBER,
    estado             CHAR(1),
    id_servicioextra_1 NUMBER NOT NULL,
    id_chofer          NUMBER NOT NULL
);

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicioextra ADD CONSTRAINT conector_departamento_servicioextra_pk PRIMARY KEY ( id_servicioextra_1
);

--  ERROR: Table name length exceeds maximum allowed length(30) 
CREATE TABLE t_conector_servicioextra_reserva (
    id_reserva         NUMBER NOT NULL,
    id_departamento    NUMBER NOT NULL,
    id_servicioextra   NUMBER NOT NULL,
    id_servicioextra_1 NUMBER NOT NULL
);

--  ERROR: PK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_servicioextra_reserva
    ADD CONSTRAINT conector_servicioextra_reserva_pk PRIMARY KEY ( id_reserva,
                                                                   id_departamento,
                                                                   id_servicioextra );

CREATE TABLE t_departamento (
    id_departamento NUMBER NOT NULL,
    direccion       VARCHAR2(50),
    longitud        NUMBER(8),
    latitud         NUMBER(8),
    habitaciones    NUMBER,
    banios          NUMBER,
    tamanio         NUMBER(2),
    valor           NUMBER(2)
);

ALTER TABLE t_departamento ADD CONSTRAINT departamento_pk PRIMARY KEY ( id_departamento );

CREATE TABLE t_error (
    id_error    NUMBER NOT NULL,
    nombreerror VARCHAR2(50),
    descripcion VARCHAR2(200),
    fechahora   NUMBER(25),
    zona        VARCHAR2(50)
);

ALTER TABLE t_error ADD CONSTRAINT error_pk PRIMARY KEY ( id_error );

CREATE TABLE t_estadopago (
    id_estadopago NUMBER NOT NULL,
    nombre        VARCHAR2(50),
    descripcion   VARCHAR2(200)
);

ALTER TABLE t_estadopago ADD CONSTRAINT estadopago_pk PRIMARY KEY ( id_estadopago );

CREATE TABLE t_estadoreserva (
    id_estadoreserva NUMBER NOT NULL,
    nombre           VARCHAR2(50),
    descripcion      VARCHAR2(200)
);

ALTER TABLE t_estadoreserva ADD CONSTRAINT estadoreserva_pk PRIMARY KEY ( id_estadoreserva );

CREATE TABLE t_estadousuario (
    id_estadousuario NUMBER NOT NULL,
    descripcion      VARCHAR2(50)
);

ALTER TABLE t_estadousuario ADD CONSTRAINT estadousuario_pk PRIMARY KEY ( id_estadousuario );

CREATE TABLE t_foto (
    id_foto         NUMBER NOT NULL,
    id_departamento NUMBER NOT NULL,
    ruta            VARCHAR2(50)
);

ALTER TABLE t_foto ADD CONSTRAINT foto_pk PRIMARY KEY ( id_foto );

CREATE TABLE t_iventario (
    id_inventario   NUMBER NOT NULL,
    nombre          VARCHAR2(50),
    cantidad        NUMBER,
    id_departamento NUMBER NOT NULL
);

ALTER TABLE t_iventario ADD CONSTRAINT iventario_pk PRIMARY KEY ( id_inventario );

CREATE TABLE t_mantencion (
    id_mantencion          NUMBER NOT NULL,
    id_categoriamantencion NUMBER NOT NULL,
    id_departamento        NUMBER NOT NULL,
    descripcion            VARCHAR2(200),
    valor                  NUMBER(2),
    fechainicio            NUMBER(25),
    fechafin               NUMBER(25)
);

ALTER TABLE t_mantencion ADD CONSTRAINT mantencion_pk PRIMARY KEY ( id_mantencion );

CREATE TABLE t_pago (
    id_pago       NUMBER NOT NULL,
    id_estadopago NUMBER NOT NULL,
    valor         NUMBER(2),
    fecha         NUMBER(25)
);

ALTER TABLE t_pago ADD CONSTRAINT pago_pk PRIMARY KEY ( id_pago );

CREATE TABLE t_permiso (
    id_permiso  NUMBER NOT NULL,
    nombre      VARCHAR2(4000),
    descripcion VARCHAR2(4000)
);

ALTER TABLE t_permiso ADD CONSTRAINT permiso_pk PRIMARY KEY ( id_permiso );

CREATE TABLE t_reporte (
    id_reporte   NUMBER NOT NULL,
    ruta         VARCHAR2(50),
    id_categoria NUMBER NOT NULL
);

ALTER TABLE t_reporte ADD CONSTRAINT reporte_pk PRIMARY KEY ( id_reporte );

CREATE TABLE t_reserva (
    id_reserva       NUMBER NOT NULL,
    id_departamento  NUMBER NOT NULL,
    id_estadoreserva NUMBER NOT NULL,
    fechadesde       NUMBER(25),
    fechahasta       NUMBER(25),
    valortotal       NUMBER,
    id_pago          NUMBER NOT NULL,
    id_usuario       NUMBER NOT NULL
);

ALTER TABLE t_reserva ADD CONSTRAINT reserva_pk PRIMARY KEY ( id_reserva );

CREATE TABLE t_servicio (
    id_servicio          NUMBER NOT NULL,
    descripcion          VARCHAR2(100),
    id_categoriaservicio NUMBER NOT NULL
);

ALTER TABLE t_servicio ADD CONSTRAINT servicio_pk PRIMARY KEY ( id_servicio );

CREATE TABLE t_sesion (
    id_sesion     NUMBER NOT NULL,
    llave         VARCHAR2(64),
    expiracion    NUMBER(25),
    id_usuario    NUMBER NOT NULL,
    fechacreacion NUMBER(25)
);

ALTER TABLE t_sesion ADD CONSTRAINT sesion_pk PRIMARY KEY ( id_sesion );

CREATE TABLE t_usuario (
    id_usuario       NUMBER NOT NULL,
    password         VARCHAR2(80),
    id_permiso       NUMBER NOT NULL,
    id_estadousuario NUMBER NOT NULL,
    email            VARCHAR2(50),
    primernombre     VARCHAR2(50),
    segundonombre    VARCHAR2(50),
    primerapellido   VARCHAR2(50),
    segundoapellido  VARCHAR2(50),
    direccion        VARCHAR2(50),
    telefono         VARCHAR2(50),
    rutafotoperfil   VARCHAR2(50)
);

ALTER TABLE t_usuario ADD CONSTRAINT usuario_pk PRIMARY KEY ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicio
    ADD CONSTRAINT t_conector_departamento_servicio_t_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES t_departamento ( id_departamento );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicio
    ADD CONSTRAINT t_conector_departamento_servicio_t_servicio_fk FOREIGN KEY ( id_servicio )
        REFERENCES t_servicio ( id_servicio );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicioextra
    ADD CONSTRAINT t_conector_departamento_servicioextra_t_categoriaservicioextra_fk FOREIGN KEY ( id_servicioextra )
        REFERENCES t_categoriaservicioextra ( id_servicioextra );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicioextra
    ADD CONSTRAINT t_conector_departamento_servicioextra_t_chofer_fk FOREIGN KEY ( id_chofer )
        REFERENCES t_chofer ( id_chofer );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_departamento_servicioextra
    ADD CONSTRAINT t_conector_departamento_servicioextra_t_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES t_departamento ( id_departamento );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_servicioextra_reserva
    ADD CONSTRAINT t_conector_servicioextra_reserva_t_conector_departamento_servicioextra_fk FOREIGN KEY ( id_servicioextra_1 )
        REFERENCES t_conector_departamento_servicioextra ( id_servicioextra_1 );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_conector_servicioextra_reserva
    ADD CONSTRAINT t_conector_servicioextra_reserva_t_reserva_fk FOREIGN KEY ( id_reserva )
        REFERENCES t_reserva ( id_reserva );

ALTER TABLE t_foto
    ADD CONSTRAINT t_foto_t_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES t_departamento ( id_departamento );

ALTER TABLE t_iventario
    ADD CONSTRAINT t_iventario_t_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES t_departamento ( id_departamento );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_mantencion
    ADD CONSTRAINT t_mantencion_t_categoriamantencion_fk FOREIGN KEY ( id_categoriamantencion )
        REFERENCES t_categoriamantencion ( id_categoriamantencion );

ALTER TABLE t_mantencion
    ADD CONSTRAINT t_mantencion_t_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES t_departamento ( id_departamento );

ALTER TABLE t_pago
    ADD CONSTRAINT t_pago_t_estadopago_fk FOREIGN KEY ( id_estadopago )
        REFERENCES t_estadopago ( id_estadopago );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_reporte
    ADD CONSTRAINT t_reporte_t_categoriareporte_fk FOREIGN KEY ( id_categoria )
        REFERENCES t_categoriareporte ( id_categoria );

ALTER TABLE t_reserva
    ADD CONSTRAINT t_reserva_t_departamento_fk FOREIGN KEY ( id_departamento )
        REFERENCES t_departamento ( id_departamento );

ALTER TABLE t_reserva
    ADD CONSTRAINT t_reserva_t_estadoreserva_fk FOREIGN KEY ( id_estadoreserva )
        REFERENCES t_estadoreserva ( id_estadoreserva );

ALTER TABLE t_reserva
    ADD CONSTRAINT t_reserva_t_pago_fk FOREIGN KEY ( id_pago )
        REFERENCES t_pago ( id_pago );

ALTER TABLE t_reserva
    ADD CONSTRAINT t_reserva_t_usuario_fk FOREIGN KEY ( id_usuario )
        REFERENCES t_usuario ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE t_servicio
    ADD CONSTRAINT t_servicio_t_categoriaservicio_fk FOREIGN KEY ( id_categoriaservicio )
        REFERENCES t_categoriaservicio ( id_categoriaservicio );

ALTER TABLE t_sesion
    ADD CONSTRAINT t_sesion_t_usuario_fk FOREIGN KEY ( id_usuario )
        REFERENCES t_usuario ( id_usuario );

ALTER TABLE t_usuario
    ADD CONSTRAINT t_usuario_t_estadousuario_fk FOREIGN KEY ( id_estadousuario )
        REFERENCES t_estadousuario ( id_estadousuario );

ALTER TABLE t_usuario
    ADD CONSTRAINT t_usuario_t_permiso_fk FOREIGN KEY ( id_permiso )
        REFERENCES t_permiso ( id_permiso );

CREATE SEQUENCE t_categoriaservicioextra_id_se START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_categoriaservicioextra_id_se BEFORE
    INSERT ON t_categoriaservicioextra
    FOR EACH ROW
    WHEN ( new.id_servicioextra IS NULL )
BEGIN
    :new.id_servicioextra := t_categoriaservicioextra_id_se.nextval;
END;
/

CREATE SEQUENCE t_departamento_id_departamento START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_departamento_id_departamento BEFORE
    INSERT ON t_departamento
    FOR EACH ROW
    WHEN ( new.id_departamento IS NULL )
BEGIN
    :new.id_departamento := t_departamento_id_departamento.nextval;
END;
/

CREATE SEQUENCE t_error_id_error_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_error_id_error_trg BEFORE
    INSERT ON t_error
    FOR EACH ROW
    WHEN ( new.id_error IS NULL )
BEGIN
    :new.id_error := t_error_id_error_seq.nextval;
END;
/

CREATE SEQUENCE t_foto_id_foto_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_foto_id_foto_trg BEFORE
    INSERT ON t_foto
    FOR EACH ROW
    WHEN ( new.id_foto IS NULL )
BEGIN
    :new.id_foto := t_foto_id_foto_seq.nextval;
END;
/

CREATE SEQUENCE t_iventario_id_inventario_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_iventario_id_inventario_trg BEFORE
    INSERT ON t_iventario
    FOR EACH ROW
    WHEN ( new.id_inventario IS NULL )
BEGIN
    :new.id_inventario := t_iventario_id_inventario_seq.nextval;
END;
/

CREATE SEQUENCE t_mantencion_id_mantencion_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_mantencion_id_mantencion_trg BEFORE
    INSERT ON t_mantencion
    FOR EACH ROW
    WHEN ( new.id_mantencion IS NULL )
BEGIN
    :new.id_mantencion := t_mantencion_id_mantencion_seq.nextval;
END;
/

CREATE SEQUENCE t_pago_id_pago_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_pago_id_pago_trg BEFORE
    INSERT ON t_pago
    FOR EACH ROW
    WHEN ( new.id_pago IS NULL )
BEGIN
    :new.id_pago := t_pago_id_pago_seq.nextval;
END;
/

CREATE SEQUENCE t_reporte_id_reporte_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_reporte_id_reporte_trg BEFORE
    INSERT ON t_reporte
    FOR EACH ROW
    WHEN ( new.id_reporte IS NULL )
BEGIN
    :new.id_reporte := t_reporte_id_reporte_seq.nextval;
END;
/

CREATE SEQUENCE t_reserva_id_reserva_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_reserva_id_reserva_trg BEFORE
    INSERT ON t_reserva
    FOR EACH ROW
    WHEN ( new.id_reserva IS NULL )
BEGIN
    :new.id_reserva := t_reserva_id_reserva_seq.nextval;
END;
/

CREATE SEQUENCE t_servicio_id_servicio_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_servicio_id_servicio_trg BEFORE
    INSERT ON t_servicio
    FOR EACH ROW
    WHEN ( new.id_servicio IS NULL )
BEGIN
    :new.id_servicio := t_servicio_id_servicio_seq.nextval;
END;
/

CREATE SEQUENCE t_sesion_id_sesion_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_sesion_id_sesion_trg BEFORE
    INSERT ON t_sesion
    FOR EACH ROW
    WHEN ( new.id_sesion IS NULL )
BEGIN
    :new.id_sesion := t_sesion_id_sesion_seq.nextval;
END;
/

CREATE SEQUENCE t_usuario_id_usuario_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER t_usuario_id_usuario_trg BEFORE
    INSERT ON t_usuario
    FOR EACH ROW
    WHEN ( new.id_usuario IS NULL )
BEGIN
    :new.id_usuario := t_usuario_id_usuario_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             0
-- ALTER TABLE                             44
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          12
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         12
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  16
-- WARNINGS                                 0
