INSERT INTO T_Region (ID_Region, Nombre) VALUES (1,  'Tarapacá');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (2,  'Antofagasta');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (3,  'Atacama');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (4,  'Coquimbo');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (5,  'Valparaíso');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (6,  'Libertador General Bernardo O`Higgins');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (7,  'Maule');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (8,  'Biobío');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (9,  'La Araucanía');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (10, 'Los Lagos');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (11, 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (12, 'Magallanes y de la Antártica Chilena');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (13, 'Metropolitana de Santiago');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (14, 'Los Ríos');
INSERT INTO T_Region (ID_Region, Nombre) VALUES (15, 'Arica y Parinacota');

INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1101,	1,	'Iquique');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1107,	1,	'Alto Hospicio');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1401,	1,	'Pozo Almonte');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1402,	1,	'Camiña');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1403,	1,	'Colchane');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1404,	1,	'Huara');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (1405,	1,	'Pica');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2101,	2,	'Antofagasta');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2102,	2,	'Mejillones');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2103,	2,	'Sierra Gorda');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2104,	2,	'Taltal');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2201,	2,	'Calama');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2202,	2,	'Ollague');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2203,	2,	'San Pedro De Atacama');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2301,	2,	'Tocopilla');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (2302,	2,	'María Elena');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3101,	3,	'Copiapó');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3102,	3,	'Caldera');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3103,	3,	'Tierra Amarilla');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3201,	3,	'Chañaral');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3202,	3,	'Diego De Almagro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3301,	3,	'Vallenar');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3302,	3,	'Alto Del Carmen');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3303,	3,	'Freirina');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (3304,	3,	'Huasco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4101,	4,	'La Serena');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4102,	4,	'Coquimbo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4103,	4,	'Andacollo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4104,	4,	'La Higuera');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4105,	4,	'Paiguano');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4106,	4,	'Vicuña');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4201,	4,	'Illapel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4202,	4,	'Canela');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4203,	4,	'Los Vilos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4204,	4,	'Salamanca');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4301,	4,	'Ovalle');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4302,	4,	'Combarbalá');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4303,	4,	'Monte Patria');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4304,	4,	'Punitaqui');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (4305,	4,	'Río Hurtado');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5101,	5,	'Valparaíso');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5102,	5,	'Casablanca');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5103,	5,	'Concón');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5104,	5,	'Juan Fernández');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5105,	5,	'Puchuncaví');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5107,	5,	'Quintero');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5109,	5,	'Viña Del Mar');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5201,	5,	'Isla De Pascua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5301,	5,	'Los Andes');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5302,	5,	'Calle Larga');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5303,	5,	'Rinconada');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5304,	5,	'San Esteban');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5401,	5,	'La Ligua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5402,	5,	'Cabildo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5403,	5,	'Papudo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5404,	5,	'Petorca');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5405,	5,	'Zapallar');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5501,	5,	'Quillota');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5502,	5,	'Calera');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5503,	5,	'Hijuelas');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5504,	5,	'La Cruz');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5506,	5,	'Nogales');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5601,	5,	'San Antonio');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5602,	5,	'Algarrobo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5603,	5,	'Cartagena');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5604,	5,	'El Quisco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5605,	5,	'El Tabo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5606,	5,	'Santo Domingo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5701,	5,	'San Felipe');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5702,	5,	'Catemu');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5703,	5,	'Llaillay');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5704,	5,	'Panquehue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5705,	5,	'Putaendo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5706,	5,	'Santa María');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5801,	5,	'Quilpué');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5802,	5,	'Limache');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5803,	5,	'Olmué');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (5804,	5,	'Villa Alemana');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6101,	6,	'Rancagua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6102,	6,	'Codegua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6103,	6,	'Coinco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6104,	6,	'Coltauco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6105,	6,	'Doñihue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6106,	6,	'Graneros');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6107,	6,	'Las Cabras');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6108,	6,	'Machali');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6109,	6,	'Malloa');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6110,	6,	'Mostazal');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6111,	6,	'El Olivar');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6112,	6,	'Peumo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6113,	6,	'Pichidegua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6114,	6,	'Quinta De Tilcoco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6115,	6,	'Rengo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6116,	6,	'Requinoa');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6117,	6,	'San Vicente');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6201,	6,	'Pichilemu');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6202,	6,	'La Estrella');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6203,	6,	'Litueche');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6204,	6,	'Marchihue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6205,	6,	'Navidad');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6206,	6,	'Paredones');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6301,	6,	'San Fernando');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6302,	6,	'Chépica');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6303,	6,	'Chimbarongo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6304,	6,	'Lolol');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6305,	6,	'Nancagua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6306,	6,	'Palmilla');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6307,	6,	'Peralillo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6308,	6,	'Placilla');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6309,	6,	'Pumanque');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (6310,	6,	'Santa Cruz');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7101,	7,	'Talca');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7102,	7,	'Constitución');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7103,	7,	'Curepto');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7104,	7,	'Empedrado');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7105,	7,	'Maule');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7106,	7,	'Pelarco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7107,	7,	'Pencahue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7108,	7,	'Río Claro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7109,	7,	'San Clemente');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7110,	7,	'San Rafael');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7201,	7,	'Cauquenes');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7202,	7,	'Chanco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7203,	7,	'Pelluhue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7301,	7,	'Curicó');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7302,	7,	'Hualañe');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7303,	7,	'Licantén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7304,	7,	'Molina');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7305,	7,	'Rauco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7306,	7,	'Romeral');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7307,	7,	'Sagrada Familia');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7308,	7,	'Teno');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7309,	7,	'Vichuquén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7401,	7,	'Linares');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7402,	7,	'Colbún');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7403,	7,	'Longaví');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7404,	7,	'Parral');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7405,	7,	'Retiro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7406,	7,	'San Javier');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7407,	7,	'Villa Alegre');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (7408,	7,	'Yerbas Buenas');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8101,	8,	'Concepción');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8102,	8,	'Coronel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8103,	8,	'Chiguayante');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8104,	8,	'Florida');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8105,	8,	'Hualqui');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8106,	8,	'Lota');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8107,	8,	'Penco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8108,	8,	'San Pedro de la Paz');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8109,	8,	'Santa Juana');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8110,	8,	'Talcahuano');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8111,	8,	'Tomé');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8112,	8,	'Hualpén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8201,	8,	'Lebu');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8202,	8,	'Arauco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8203,	8,	'Cañete');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8204,	8,	'Contulmo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8205,	8,	'Curanilahue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8206,	8,	'Los Alamos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8207,	8,	'Tirua');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8301,	8,	'Los Angeles');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8302,	8,	'Antuco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8303,	8,	'Cabrero');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8304,	8,	'Laja');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8305,	8,	'Mulchén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8306,	8,	'Nacimiento');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8307,	8,	'Negrete');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8308,	8,	'Quilaco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8309,	8,	'Quilleco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8310,	8,	'San Rosendo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8311,	8,	'Santa Bárbara');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8312,	8,	'Tucapel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8313,	8,	'Yumbel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8314,	8,	'Alto Biobío');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8401,	8,	'Chillán');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8402,	8,	'Bulnes');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8403,	8,	'Cobquecura');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8404,	8,	'Coelemu');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8405,	8,	'Coihueco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8406,	8,	'Chillán Viejo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8407,	8,	'El Carmen');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8408,	8,	'Ninhue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8409,	8,	'Ñiquén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8410,	8,	'Pemuco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8411,	8,	'Pinto');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8412,	8,	'Portezuelo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8413,	8,	'Quillón');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8414,	8,	'Quirihue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8415,	8,	'Ranquil');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8416,	8,	'San Carlos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8417,	8,	'San Fabián');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8418,	8,	'San Ignacio');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8419,	8,	'San Nicolás');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8420,	8,	'Treguaco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (8421,	8,	'Yungay');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9101,	9,	'Temuco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9102,	9,	'Carahue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9103,	9,	'Cunco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9104,	9,	'Curarrehue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9105,	9,	'Freire');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9106,	9,	'Galvarino');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9107,	9,	'Gorbea');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9108,	9,	'Lautaro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9109,	9,	'Loncoche');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9110,	9,	'Melipeuco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9111,	9,	'Nueva Imperial');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9112,	9,	'Padre Las Casas');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9113,	9,	'Perquenco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9114,	9,	'Pitrufquén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9115,	9,	'Pucón');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9116,	9,	'Saavedra');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9117,	9,	'Teodoro Schmidt');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9118,	9,	'Toltén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9119,	9,	'Vilcún');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9120,	9,	'Villarrica');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9121,	9,	'Cholchol');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9201,	9,	'Angol');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9202,	9,	'Collipulli');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9203,	9,	'Curacautín');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9204,	9,	'Ercilla');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9205,	9,	'Lonquimay');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9206,	9,	'Los Sauces');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9207,	9,	'Lumaco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9208,	9,	'Puren');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9209,	9,	'Renaico');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9210,	9,	'Traiguén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (9211,	9,	'Victoria');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10101,	10,	'Puerto Montt');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10102,	10,	'Calbuco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10103,	10,	'Cochamó');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10104,	10,	'Fresia');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10105,	10,	'Frutillar');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10106,	10,	'Los Muermos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10107,	10,	'Llanquihue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10108,	10,	'Maullín');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10109,	10,	'Puerto Varas');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10201,	10,	'Castro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10202,	10,	'Ancud');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10203,	10,	'Chonchi');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10204,	10,	'Curaco de Velez');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10205,	10,	'Dalcahue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10206,	10,	'Puqueldón');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10207,	10,	'Queilén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10208,	10,	'Quellón');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10209,	10,	'Quemchi');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10210,	10,	'Quinchao');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10301,	10,	'Osorno');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10302,	10,	'Puerto Octay');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10303,	10,	'Purranque');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10304,	10,	'Puyehue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10305,	10,	'Río Negro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10306,	10,	'San Juan de la Costa');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10307,	10,	'San Pablo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10401,	10,	'Chaitén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10402,	10,	'Futaleufú');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10403,	10,	'Hualaihue');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (10404,	10,	'Palena');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11101,	11,	'Coihayque');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11102,	11,	'Lago Verde');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11201,	11,	'Aisén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11202,	11,	'Cisnes');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11203,	11,	'Guaitecas');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11301,	11,	'Cochrane');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11302,	11,	'O`Higgins');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11303,	11,	'Tortel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11401,	11,	'Chile Chico');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (11402,	11,	'Río Ibáñez');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12101,	12,	'Punta Arenas');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12102,	12,	'Laguna Blanca');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12103,	12,	'Río Verde');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12104,	12,	'San Gregorio');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12201,	12,	'Cabo de Hornos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12202,	12,	'Antártica');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12301,	12,	'Porvenir');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12302,	12,	'Primavera');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12303,	12,	'Timaukel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12401,	12,	'Natales');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (12402,	12,	'Torres del Paine');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13101,	13,	'Santiago');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13102,	13,	'Cerrillos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13103,	13,	'Cerro Navia');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13104,	13,	'Conchalí');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13105,	13,	'El Bosque');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13106,	13,	'Estación Central');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13107,	13,	'Huechuraba');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13108,	13,	'Independencia');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13109,	13,	'La Cisterna');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13110,	13,	'La Florida');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13111,	13,	'La Granja');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13112,	13,	'La Pintana');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13113,	13,	'La Reina');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13114,	13,	'Las Condes');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13115,	13,	'Lo Barnechea');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13116,	13,	'Lo Espejo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13117,	13,	'Lo Prado');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13118,	13,	'Macul');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13119,	13,	'Maipú');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13120,	13,	'Ñuñoa');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13121,	13,	'Pedro Aguirre Cerda');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13122,	13,	'Peñalolén');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13123,	13,	'Providencia');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13124,	13,	'Pudahuel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13125,	13,	'Quilicura');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13126,	13,	'Quinta Normal');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13127,	13,	'Recoleta');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13128,	13,	'Renca');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13129,	13,	'San Joaquín');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13130,	13,	'San Miguel');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13131,	13,	'San Ramón');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13132,	13,	'Vitacura');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13201,	13,	'Puente Alto');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13202,	13,	'Pirque');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13203,	13,	'San José De Maipo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13301,	13,	'Colina');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13302,	13,	'Lampa');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13303,	13,	'Tiltil');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13401,	13,	'San Bernardo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13402,	13,	'Buin');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13403,	13,	'Calera De Tango');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13404,	13,	'Paine');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13501,	13,	'Melipilla');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13502,	13,	'Alhué');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13503,	13,	'Curacaví');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13504,	13,	'María Pinto');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13505,	13,	'San Pedro');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13601,	13,	'Talagante');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13602,	13,	'El Monte');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13603,	13,	'Isla De Maipo');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13604,	13,	'Padre Hurtado');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (13605,	13,	'Peñaflor');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14101,	14,	'Valdivia');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14102,	14,	'Corral');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14103,	14,	'Lanco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14104,	14,	'Los Lagos');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14105,	14,	'Máfil');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14106,	14,	'Mariquina');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14107,	14,	'Paillaco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14108,	14,	'Panguipulli');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14201,	14,	'La Unión');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14202,	14,	'Futrono');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14203,	14,	'Lago Ranco');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (14204,	14,	'Río Bueno');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (15101,	15,	'Arica');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (15102,	15,	'Camarones');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (15201,	15,	'Putre');
INSERT INTO T_Comuna (ID_Comuna, ID_Region, Nombre) VALUES (15202,	15,	'General Lagos');
