CREATE OR REPLACE TRIGGER TRG_SERVICIOEXTRACONTRATADO_VALOR BEFORE
    INSERT ON T_SERVICIOEXTRA_CONTRATADO
    FOR EACH ROW
    WHEN ( NEW.VALOR IS NULL )
DECLARE
    X_ID_EXTSRV NUMBER;
BEGIN
    SELECT VALOR INTO X_ID_EXTSRV 
    FROM T_SERVICIOEXTRA WHERE ID_SERVICIOEXTRA = :NEW.ID_SERVICIOEXTRA;
    :NEW.VALOR := X_ID_EXTSRV;
END;